name: oidc
on:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  call-eks-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      work-dir: "./"
      aws-region: "us-east-1"
    secrets:
      CI_ROLE: ${{ secrets.CI_ROLE }}
      TERRAFORM_WORKFLOW: ${{ secrets.TERRAFORM_WORKFLOW  }}